<html>
  <head>
    <title>Hacker News</title>
    <style>
      body,html{
        margin:0;
        padding:0;
      }
    </style>
  </head>
  <body>
    <iframe 
      width='100%' 
      height='100%' 
      frameborder='0'
      src="https://view.officeapps.live.com/op/view.aspx?src=https://dn-mhc.qbox.me/filePreview20190928/excel/excelTest.xlsx"
    ></iframe>
  </body>
</html>